quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=8527
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/sistema_vendas

quarkus.hibernate-orm.schema-management.strategy=update